name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: application YAML 파일 생성
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}"          > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_JWT_YML }}"     > src/main/resources/application-jwt.yml
          echo "${{ secrets.APPLICATION_MYSQL_YML }}"   > src/main/resources/application-mysql.yml
          echo "${{ secrets.APPLICATION_OAUTH_YML }}"   > src/main/resources/application-oauth.yml
          echo "${{ secrets.APPLICATION_SWAGGER_YML }}" > src/main/resources/application-swagger.yml
          echo "${{ secrets.APPLICATION_SES_YML }}" > src/main/resources/application-ses.yml

      - name: Gradle Wrapper 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Spring Boot 빌드 (bootJar)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean bootJar
          cache-disabled: true

      - name: Docker 이미지 빌드 및 푸시
        run: |
          docker build -t hub.klr.kr/chulcheck_back .
          docker push hub.klr.kr/chulcheck_back

  deploy-backend:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Docker 이미지 풀
        run: docker pull hub.klr.kr/chulcheck_back

      - name: 기존 컨테이너 중지
        run: docker stop chulcheck_back || true

      - name: 기존 컨테이너 제거
        run: docker rm   chulcheck_back || true

      - name: 신규 컨테이너 실행
        run: |
          docker run -d \
            --name    chulcheck_back \
            --network server         \
            hub.klr.kr/chulcheck_back
